apiVersion: v1
kind: ConfigMap
metadata:
  name: kanban-api
data:
  application.properties: |
    keycloak.auth-server-url=http://192.168.64.5:30837/auth
    keycloak.realm=kanban
    keycloak.resource=a742dfd1-8540-4d2f-b870-064b33051bb3
    keycloak.security-constraints[0].authRoles[0]=user
---
apiVersion: v1
kind: Service
metadata:
  name: kanban-api
  labels:
    app: kanban-api
spec:
  ports:
    - name: http
      port: 3001
      targetPort: 3001
  selector:
    app: kanban-api
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kanban-api
  namespace: default
  labels:
    app: kanban-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kanban-api
  template:
    metadata:
      labels:
        app: kanban-api
    spec:
      containers:
        - name: kanban-api
          image: kanban-api:latest
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 3001
          volumeMounts:
            - name: kanban-api
              mountPath: /workspace/config
      volumes:
        - name: kanban-api
          configMap:
            name: kanban-api